[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/reverse-proxy-basepath"
  to = "https://nextjs-dynamic-path.netlify.app/reverse-proxy-basepath"
  status = 200

[[redirects]]
  from = "/reverse-proxy-basepath/*"
  to = "https://nextjs-dynamic-path.netlify.app/reverse-proxy-basepath/:splat"
  status = 200
